githubteacher/feb-devs

- places/Belfast.mb
This is my extended description.
It is a markdown format
It is about Belfast @githubteacher  is this ok
> Adding a file for Belfast

- Places/Sheffield-UK.md
More info about Sheffield
This issue closes #48
> Intial file for things about Sheffield UK

- places/belfast-northernireland
This PR closes #36 
Emojis :+1:
> Adding a file for Belfast, Northern Ireland

- places/Croydon.md
> Added a file for Croydon

- Longford.md
The superior town in the midlands #34
> Added Longford file

- places/fuquay-varina-nc.md
This PR closes #8 
Can you put :eyes: @hcanna? Anything I should add?
> Adding a file for Fuquay Varina NC

- places/esteio-rs-brazil.md
This PR closes #6.
What do you think @githubteacher?
> Adding a file for Esteio, RS, Brazil

- places/ayy-lmao.md
> Created new ayy lmao.

- places/campo-grande-ms-brazil.md
> Adding a file for campo-grande-ms-brazil

- myplace/Bhawanipatna.md
summary
This PR closes #25 
Can you put :+1: @sumanth51 ?
> initial file

- places/hamilton-bermuda.md
This PR closes #7 
What do you think @kenmoran1980? :hankey:
> Adding a file for Hamilton Bermuda

- places/orange-county-ca.md
This Poll Request closes #25 
What do you think @hcanna ? :eyeglasses:
> Adding a file for orange county nc

- places/penzance-cornwall-uk.md
- This PR closes #23 by @simondass
> Initial file for Penzance, Cornwall, UK

- places/schwalldorf.md
Info about Schwalldorf. 
#38 
Listen :ear: @klausfink @maknecht
> Iniital file for Schwalldorf

- places/Dublin.md
This closes #11 
This work for you @thisisgok?
> Adding a file for Dublin

- places/rotterdam.md
This is my extended description, where everybody can understand my train of thought and collaborate.
> Adding file for rotterdam, NL

- places/Sindelfingen-bw.md
> initial file for Sindelfingen

- places/Nalgonda
This PR closes #41 
@reddygopu  hello
> Adding file  for Nalgonda

- places/hcanna-hometown.md
My methodology behind this file is to create a place for my fellow colleagues to know some great places to eat in Omaha, NE. This PR closes #45
> Added a New Place File

- places/bhongir/bhongir-desc.md
This PR closes #18 
What do you think @pratikraj11 ? Can you put :eyes: @pratikraj11 ?
> Adding a file for Bhongir

- places/Dublin-Ireland.md
This PR closes #12 by fixing #12 
@acorkery or @KyleWatkinson broke it :-1:
> Adding a file for Dublin Ireland

- places/ocotlan-mexico.md
This PR closes #54 
What do yo think @githubteacher 
can you put :eyes:
> Adding a file for Ocotlan

- hometown51/myplace.md
> added the myplace details

- places/vijayawada-ap.md
This PR closes #51 
Can u put :eyes: @jagruthichilakapati
> Adding a file for vijayawada ap

- places/warsaw.md
> Initial file for Warsaw

- BJ/newfile.md
This file tells the adding a new file to my repository 
Pull request to #42
> First file to create a pull request

- places/curekli-london.md
> curekli Adding a file for London,UK

- famous.txt
Initial file that describe my hometown
> About my Hometown

- places/sao-paulo-brazil.md
This PR closes #22 
Sup @jsaonlineuk and @irmbrady? :baby_bottle:
> Adding a file for Sao Paulo Brazil

- places/granada-spain.md
> adding file for Granada Spain

- places/givot-bar-israel.md
This is my extended description
This closes #43
> Initial file for Givot Bar, Israel

- places/Los-Angeles-CA.md
- placesLos-Angeles-CA.md
> Adding a file for Los Angeles CA

- places/ramtel-germany.md
Just added some roads.
closes #35
> New file for Ramtel, Germany

- places/Belfast.mb
> Added more to the branch

- README.md
- places/london-uk.md
This PR closes #28 @douglasreis  :+1:
> Adding a file for London, UK

- places/waterford-ireland 2.txt
- places/waterford-ireland.md
> Adding a  file for Waterford Ireland

- README.md
- places/seoul-south-korea.md
This PR closes #10 
Can you put :eyes: @irmbrady? Anything
:+1: @hcanna?
> Adding a file for Seoul, South Korea

- Places/Hyderabad.md
please close #46 
This is an extended description. This is cool @thrineshvaka
> First Pull request

- places/Bettiah.md
Kind of the thought on Home and Webinar. This PR closes #37 @kg255000 :joy_cat:
> Created HomeTown Info file plus closes the Issues.

- Places/Belfast2.mb
> Adding new content

- FIRSTFILE
It's not that much important to have a look to it.
can you put :eyes: on these @hcanna
> This is the first file I am creating

- places/schwalldorf.md
> Typos corrected

- places/Dublin.md
> Just added a word

- file2.md
- places/hcanna-hometown.md
crichID please review and let me know your changes.
> Hcanna hometown food
